server:
  port: 8080

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: NOTE-SERVICE
          uri: lb://NOTE-SERVICE
          predicates:
            - Path=/notes/**

# eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
